FROM maven:3.8.4-openjdk-17 AS build

COPY src /app/src
COPY pom.xml /app

WORKDIR /app
RUN mvn clean install

FROM openjdk:8-jre-alpine

# COPY --from=build /app/target/gestao-festa.jar /app/app.jar ?????????????????????????????????

# RUN mvn package -DskipTests
# COPY --from=build /app /app

WORKDIR /app
EXPOSE 8080

#CMD ["java", "-jar", "/app/app.jar"]

#CMD ["mvn", "spring-boot:run"]